modLoader="javafml"
loaderVersion="[4,)"
issueTrackerURL="https://github.com/Vazkii/Morph-o-Tool"
license="Creative Commons Attribution-NonCommercial-ShareAlike 3.0 Unported License"

[[mods]]
modId="morphtool"
displayName="Morph-o-Tool"
version="${file.jarVersion}"
authors="Vazkii, MoreThanHidden, Uraneptus"
description='''The wrench to end all wrenches.'''

[[dependencies.morphtool]]
    modId="neoforge"
    type="required"
    versionRange="[21.0.143,)"
    ordering="AFTER"
    side="BOTH"
[[dependencies.morphtool]]
    modId="minecraft"
    type="required"
    versionRange="[1.21,)"
    ordering="NONE"
    side="BOTH"
